### ISSUE TITLE
Возникла ошибка при попытке переименовать компонент

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#565]
Вывод консоли:
```
Uncaught Error: Попытка удалить несуществующий компонент!
    at StateMachineController.deleteComponent (StateMachineController.ts:76:13)
    at CanvasController.deleteComponent (CanvasController.ts:961:26)
    at ComponentsController.editComponent (ComponentsController.ts:90:23)
    at editComponent (CanvasController.ts:941:23)
    at CanvasController.processDrawable (CanvasController.ts:298:12)
    at ModelController.emit (EventEmitter.ts:19:11)
    at ModelController.editComponent (ModelController.ts:1184:10)
    at onEdit (useComponents.ts:95:21)
    at handleSubmit (ComponentEditModal.tsx:87:5)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
```
Пока неизвестно, что привело к этой ошибке, дальнейшие попытки переименования не вызвали проблем.

**Comment by L140-beep** [comment]
Проблема возникла из-за того, что была открыта старая схема, где существует два компонента в разных МС с одинаковым названием. Первый компонент ComponentsController создавал и передавал в StateMachineController. Второй же компонент не создавался, так как компонент с таким id уже существует в ComponentsController. Поэтому при редактировании компонента мы пытаемся изменить компонент, который не существует в StateMachineController
