### ISSUE TITLE
Краш IDE при выборе прошивки для загрузки в МС-ТЮК

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#573]
Вывод консоли:
```
TypeError: Cannot read properties of undefined (reading 'binary')
    at isFlashDisabled (ManagerMS.tsx:194:68)
    at ManagerMSTab (ManagerMS.tsx:236:80)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19588:20)
    at beginWork (react-dom.development.js:21601:16)
    at beginWork$1 (react-dom.development.js:27426:14)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)
```

**Comment by Roundabout1** [comment]
Причина: сохранение старых бинарных данных с предыдущей схемы при загрузке новой схемы

**Comment by Roundabout1** [comment]
Фикс: https://github.com/kruzhok-team/lapki-client/pull/584
