### ISSUE TITLE
Краш при удалении компонента по неизвестной причине

### ISSUE THREAD

**Issue by Roundabout1** [kruzhok-team/lapki-client#594]
Пока не удалось воспроизвести баг

```
Uncaught Error: Попытка удалить несуществующий компонент!
    at StateMachineController.deleteComponent (index-3619e031.js:75582:13)
    at deleteComponent (index-3619e031.js:77398:26)
    at CanvasController.processDrawable (index-3619e031.js:76796:12)
    at ModelController.emit (index-3619e031.js:31886:11)
    at ModelController.deleteComponent (index-3619e031.js:79423:10)
    at onDelete (index-3619e031.js:41003:21)
    at handleSubmit (index-3619e031.js:63827:5)
    at Object.Nb (index-3619e031.js:1376:8)
    at Tb (index-3619e031.js:1388:6)
    at Ub (index-3619e031.js:1391:6)
index-3619e031.js:4256 TypeError: Cannot read properties of undefined (reading 'type')
    at Object.deleteComponent (index-3619e031.js:64850:22)
    at HistoryItem (index-3619e031.js:65039:35)
    at Xh (index-3619e031.js:3791:8)
    at dj (index-3619e031.js:4404:8)
    at Wk (index-3619e031.js:6924:96)
    at Vk (index-3619e031.js:6554:12)
    at Uk (index-3619e031.js:6547:5)
    at Jk (index-3619e031.js:6530:7)
    at Ok (index-3619e031.js:6246:8)
    at Fk (index-3619e031.js:6307:32)
index-3619e031.js:80156 <🙀💩> Что-то пошло не так
index-3619e031.js:80157 TypeError: Cannot read properties of undefined (reading 'type')
    at Object.deleteComponent (index-3619e031.js:64850:22)
    at HistoryItem (index-3619e031.js:65039:35)
    at Xh (index-3619e031.js:3791:8)
    at dj (index-3619e031.js:4404:8)
    at Wk (index-3619e031.js:6924:96)
    at Vk (index-3619e031.js:6554:12)
    at Uk (index-3619e031.js:6547:5)
    at Jk (index-3619e031.js:6530:7)
    at Ok (index-3619e031.js:6246:8)
    at Fk (index-3619e031.js:6307:32)
index-3619e031.js:80158 </🙀💩>
```

**Comment by Roundabout1** [comment]
Схемоэкран не был открыт
Текстовый режим не был активирован
Платформой была либо Arduino Uno, либо Arduino Micro
Было добавлено два компонента: Button и QHsmSerial
Была составлена схема с использование QHsmSerial без использования Button
После попытки удалить Button возникла ошибка

**Comment by Roundabout1** [comment]
Список действий, которые привели к ошибке, были использованы компоненты Timer и Counter, Counter был удалён, платформа Arduino Uno
![image](https://github.com/user-attachments/assets/2265cc60-6b69-44c5-b237-1e7f422d414c)
![image](https://github.com/user-attachments/assets/b9194276-e598-4bcd-b992-a8c539fd2f95)
![image](https://github.com/user-attachments/assets/65dbb8b6-65af-4950-9a19-dfa5a163accb)
![image](https://github.com/user-attachments/assets/2e63c6cc-5942-4239-9e48-e62987a95d3b)
